version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql-agendamentos:
    image: mysql:8.0
    container_name: mysql-agendamentos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital_agendamentos
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-agendamentos-data:/var/lib/mysql

  agendamentos-api:
    build:
      context: ../agendamentos-service/Agendamentos.Api
      dockerfile: Dockerfile
    container_name: agendamentos-api
    depends_on:
      mysql-agendamentos:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "5001:8080"

  mysql-clinica:
    image: mysql:8.0
    container_name: mysql-clinica
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital_clinica
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_general_ci
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-clinica-data:/var/lib/mysql

  clinica-api:
    build:
      context: ../clinica-service/Clinica.Api
      dockerfile: Dockerfile
    container_name: clinica-api
    depends_on:
      mysql-clinica:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "5002:8080"

  mysql-cirurgico:
    image: mysql:8.0
    container_name: mysql-cirurgico    
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital_cirurgico
    ports:
      - "3309:3306"    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-cirurgico-data:/var/lib/mysql

  cirurgico-api:
    build:
      context: ../cirurgico-service/Cirurgico.Api
      dockerfile: Dockerfile
    container_name: cirurgico-api
    environment:
      - ConnectionStrings__DefaultConnection=Server=mysql-cirurgico;Port=3306;Database=hospital_cirurgico;User=root;Password=root;
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      mysql-cirurgico:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "5003:8080"

volumes:
  mysql-agendamentos-data:
  mysql-clinica-data:
  mysql-cirurgico-data: